### ISSUE TITLE
excessive error logs

### ISSUE THREAD

**Issue by Zentheon** [Digifox03/variedMobs#10]
[latest.log](https://github.com/Digifox03/variedMobs/files/5825415/latest.log)

Not exactly sure why this occurs, especially since the only pack used in that instance was a very simple copypaste directly from the wiki. It worked perfectly fine, just spammed errors.

**Comment by Digifox03** [comment]
Please include the resource pack you are using while this error happened.

**Comment by Zentheon** [comment]
[0text.zip](https://github.com/Digifox03/variedMobs/files/5846353/0text.zip)

**Comment by FewerFlaws** [comment]
I am also getting an abusive amount of errors in the log.  It's all null pointer exceptions, and it only happens if you use a resource pack.  To troubleshoot I made a resource pack which gives pigs exactly two variants.  Something is definitely borked.
[creatureVariants.zip](https://github.com/Digifox03/variedMobs/files/5930682/creatureVariants.zip)

**Comment by FewerFlaws** [comment]
Similar to Xetheon's situation, the mod worked.  I had both types of pigs spawning successfully from eggs.  But the log is completely filled with errors, and I believe the error spam is intense enough to crash the game with a more complex resource pack.

**Comment by Digifox03** [comment]
Please reproduce the issue without other mods. If the issue cannot be reproduced then find the minimum set of mods that causes the issue. I suspect KubeJS might be the cause of the issue.
An error while loading the pack happens, which should fail the resource pack loading and disable all packs, but it is being ingnored (hence the errors spam)

**Comment by Digifox03** [comment]
Closing as stale
